"""Read modern (>= 20230327) plaso storage files directly via stdlib sqlite3.

See ``docs/superpowers/specs/2026-05-14-plaso-ingest-design.md`` for the
on-disk format we depend on.
"""
from __future__ import annotations

import sqlite3
import zlib
from collections.abc import Iterator
from pathlib import Path

import orjson


_MIN_FORMAT_VERSION = 20230327

_JOIN_SQL = """
SELECT e.timestamp, e.timestamp_desc, ed._data
FROM event e
JOIN event_data ed
  ON ed._identifier = CAST(
       substr(e._event_data_identifier, instr(e._event_data_identifier, '.') + 1)
     AS INTEGER)
ORDER BY e.timestamp
"""


class PlasoFormatError(Exception):
    """The file is a plaso SQLite store, but the version or serializer is not supported."""


def event_count(path: Path) -> int:
    """Return the number of event rows in a plaso storage file."""
    uri = f"file:{Path(path)}?mode=ro"
    with sqlite3.connect(uri, uri=True) as con:
        return int(con.execute("SELECT COUNT(*) FROM event").fetchone()[0])


def iter_events(path: Path) -> Iterator[dict]:
    """Yield event payload dicts from a modern plaso storage file.

    Each yielded dict has ``timestamp`` (microseconds since epoch),
    ``timestamp_desc``, and every field plaso wrote into the event_data
    payload (``data_type``, ``display_name``, parser-specific keys, ...).

    Plaso stores no ``message`` in ``event_data`` — that field is generated by
    per-``data_type`` formatter plugins inside ``psort``. We synthesise a
    fallback message from the most informative available field so the timeline
    view isn't empty.
    """
    path = Path(path)
    uri = f"file:{path}?mode=ro"
    with sqlite3.connect(uri, uri=True) as con:
        meta = dict(con.execute("SELECT key, value FROM metadata"))
        _validate(meta)
        compressed = meta.get("compression_format", "none") == "zlib"
        for ts_usec, ts_desc, blob in con.execute(_JOIN_SQL):
            data = zlib.decompress(blob) if compressed else bytes(blob)
            payload = orjson.loads(data)
            payload.pop("__type__", None)
            payload.pop("__container_type__", None)
            payload["timestamp"] = int(ts_usec) if ts_usec is not None else 0
            payload["timestamp_desc"] = ts_desc or ""
            if not payload.get("message"):
                payload["message"] = _synthesize_message(payload)
            yield payload


_MESSAGE_FALLBACK_FIELDS: tuple[str, ...] = (
    "text", "data", "body", "xml_string", "query",
    "display_name", "filename", "url", "title",
    "username", "user", "command",
)
_MESSAGE_MAX_LEN = 500


def _synthesize_message(payload: dict) -> str:
    """Pick the first informative string field as a fallback message."""
    for key in _MESSAGE_FALLBACK_FIELDS:
        v = payload.get(key)
        if isinstance(v, str) and v.strip():
            return v if len(v) <= _MESSAGE_MAX_LEN else v[:_MESSAGE_MAX_LEN] + "…"
    data_type = payload.get("data_type") or ""
    return str(data_type)


def _validate(meta: dict[str, str]) -> None:
    serializer = meta.get("serialization_format", "")
    if serializer != "json":
        raise PlasoFormatError(
            f"unsupported serialization_format: {serializer!r}; expected 'json'"
        )
    try:
        version = int(meta.get("format_version", "0"))
    except ValueError:
        version = 0
    if version < _MIN_FORMAT_VERSION:
        raise PlasoFormatError(
            f"plaso format version {version} is too old (need >= {_MIN_FORMAT_VERSION}). "
            "Re-export with a recent plaso version, or pre-process with "
            "`psort -o json_line -w timeline.jsonl <file>` and import the JSONL."
        )
